version: '3.10'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq

  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongodb

